### ISSUE TITLE
Add MACE

### ISSUE THREAD

**Issue by jcklie** [Toloka/crowd-kit#5]
Is it possible that you add [MACE](https://aclanthology.org/N13-1132.pdf) ? It is often used in my field but there is only a Java implementation that is hard to integrate into Python projects.

**Comment by dustalov** [comment]
Thank you for reaching us! I have added MACE to our internal roadmap. Since this method is similar to the already present Dawid-Skene and to-be-added-soon GLAD methods, could you please provide us with an example showing a significant quality boost?

**Comment by jcklie** [comment]
Thank you! I think the performance between the two is pretty similar (see [this evaluation](http://www.dirkhovy.com/portfolio/papers/download/bma_draft.pdf)), the main difference from what I see is that D&S provides a
confusion matrix as a side result whereas MACE shows the spamming preference and the credibility of annotators.

**Comment by dustalov** [comment]
There is a single-coin variation of the Dawid-Skene model that uses reliability levels instead of confusion matrices. It is in our roadmap, too. We will consider adding MACE, but from what I know, it is not always enough to model spamming preference in a single parameter. In that [evaluation paper](https://aclanthology.org/Q18-1040.pdf), MACE was on par with Dawid-Skene (thank you for the reference).

**Comment by dustalov** [comment]
Added by @pilot7747. @jcklie please try it out!
