### ISSUE TITLE
[DOCS]  Links in the README file are almost all broken

### ISSUE THREAD

**Issue by johann-petrak** [Toloka/crowd-kit#59]
### Problem description

On page https://github.com/Toloka/crowd-kit click on e.g. any of the Method links under Categorical Responses, they all lead to a 404 Error. 

However, these links work on the https://toloka.ai/docs/crowd-kit/ page. 

### Documentation links

https://github.com/Toloka/crowd-kit/blob/main/README.md

**Comment by dustalov** [comment]
Dear Johann, thank you for the report!

The problem was introduced in #51 when for the convenience of documentation generation the links were manually rewritten.

@alexandervnuchkov @DrhF @alexdrydew, I see two different ways for fixing this:

1. change it back and update the documentation building script so that it rewrites the URLs, or
2. use the absolute links to the documentation at https://toloka.ai/docs/crowd-kit/

What do you think?

**Comment by DrhF** [comment]
Dear Johann, thanks for the report!

@dustalov Thank you for suggestions! As for me, the second option (use of absolute links to docs) is more preferable. If @alexandervnuchkov and @alexdrydew agree, I may create PR with relevant fixes

**Comment by alexandervnuchkov** [comment]
@dustalov https://github.com/Toloka/crowd-kit/pull/65 please take a look.
